Density button/dev
EvolutionSimulator/EvolutionSimulator pull request #50
Opened 2023-12-11 12:47 UTC by magda9s

Adding creature density button

2023-12-11 13:49 UTC, Charlielv04 requested changes
Rebase before merging

2023-12-12 00:06 UTC, magda9s commented
> Rebase before merging

Rebased done. There is no project branch so pull requesting to main.

2023-12-12 08:46 UTC, Charlielv04 approved these changes

2023-12-12 08:48 UTC, Charlielv04 approved these changes
looks good to me

2023-12-12 08:48 UTC, merged